import Head from "next/head";
// import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  // RENDERING CODE

  return (
    <>
      {/* TO GIVE ACCES TO OTHER FILES WE USE GLOBAL KEYWORD */}
      {/* <style jsx global> */}
      <style jsx>
        {
          `
            .webTitle{
              color:red
            }
            .webSubTitle{
              color:#2b02fd
            }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="next, blog, hunting coder, nextjs" />
        {/* SIMPLE SCRIPT TAG IS ADDED HERE */}
        {/* <script src='sc.js'></script> */}
      </Head>
      {/* NEXT SCRIPT TAG IS ADDED HERE */}
      {/* <Script src='sc.js' strategy='lazyOnload'></Script> */}
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.description} blogsBox`}>
          <h1 className={`${styles.customFontH1} ${styles.webTitle} `}>Hunting Coder</h1>
          <h2 className={`${styles.customFontH2} ${styles.webSubTitle} `}>
            A blog for hunting coder by a hunting coder!
          </h2>

          {/* WEBPAGE IMAGE */}
          <img src='/human.jpg' className={styles.webImg} alt="laptop" width={400} height={230} />

          <div className={styles.blogItems}>
            <h3 className={styles.customFontH3}>Latest Blogs Of 2023</h3>
            <div className={styles.blogItem}>
              <h4 className={styles.customFontH4}>How to Learn NextJs?</h4>
              <h5 className={styles.customFontH5}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptates necessitatibus eveniet ex iure accusamus quia sint
                hic rerum. Doloremque, commodi!
              </h5>
            </div>
            <div className={styles.blogItem}>
              <h4 className={styles.customFontH4}>How to Learn NextJs?</h4>
              <h5 className={styles.customFontH5}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptates necessitatibus eveniet ex iure accusamus quia sint
                hic rerum. Doloremque, commodi!
              </h5>
            </div>
            <div className={styles.blogItem}>
              <h4 className={styles.customFontH4}>How to Learn NextJs?</h4>
              <h5 className={styles.customFontH5}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptates necessitatibus eveniet ex iure accusamus quia sint
                hic rerum. Doloremque, commodi!
              </h5>
            </div>
            <div className={styles.blogItem}>
              <h4 className={styles.customFontH4}>How to Learn NextJs?</h4>
              <h5 className={styles.customFontH5}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptates necessitatibus eveniet ex iure accusamus quia sint
                hic rerum. Doloremque, commodi!
              </h5>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
